resolver: lts-18.16

packages: 
  - .
  - batchd-core/
  - batchd-docker/
  - batchd-libvirt/
  - batchd-amazonka/
  - ../heavy-logger/
  - ../heavy-logger/heavy-logger-instances/

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: 
  - optparse-applicative-0.16.1.0
  - dates-0.2.3.2
  - docker-0.6.0.6
  - libvirt-hs-0.2.1
  - libssh2-0.2.0.5
  - libssh2-conduit-0.2.1
  - hsyslog-5.0.2
  - select-0.4.0.1
  - monad-metrics-0.2.2.0
  - haskell-gettext-0.1.2.0
  - text-format-heavy-0.1.5.2
  - localize-0.2.0.0
    #- heavy-logger-0.3.2.0
  - heavy-logger-amazon-0.1.0.0
  - esqueleto-3.5.3.0
  - readline-1.0.3.0
  - wai-middleware-metrics-0.2.4
  - amazonka-1.6.1
  - amazonka-ec2-1.6.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

